### ISSUE TITLE
Future development: More TIXY

### ISSUE THREAD

**Issue by robertlipe** [robertlipe/NightDriverStrip#17]
Investigate galleries of
http://maxbittker.github.io/Mojulo/gallery.html
https://tixy.land/gallery/
https://github.com/owenmcateer/tixy.land-display/blob/main/Sketch.ino
https://editor.soulmatelights.com/gallery/475

Related: there's a whole little cottage industry around pixel art: https://divoom.com/

**Comment by davepl** [comment]
I think there are 3-4 submodes of Tixy that are really nice, and lots of silly ones.  I would make the mode a constructor arg and then not have it rotate through effects.

I would be good to do this with Picasso too, split it into Picasso 1, Picasso 2, Picasso 3 depending on how it is intialized.  Then we could, let’s say, include 1 and 3 but not 2.

I was also wondering if the Smoke effect could use the noise tables that are already in GFXBase.  I haven’t looked closely enough to know, but just pointing out we have noise tables and MoveFractionalXY already, so would be nice not to have dupes.

- Dave
